
resources:
  - name: R_GitRepo
    type: GitRepo
    configuration:
      gitProvider: github_amirydev
      path: amirydev/dev-pipelines
      branches:
        include: feature-PIPE-5768
  - name: R_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: myArti
      buildName: 'my_go_build'
      buildNumber: ${run_id}
  - name: R_ReleaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: jfdist
      name: my_go_build
      version: ${run_id}

pipelines:
  - name: pipeline_S_GoPublishBinary
    steps:
      - name: S_GoBuild
        type: GoBuild
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: my_go_build
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          inputResources:
            - name: R_GitRepo
          integrations:
            - name: myArti
          sourceLocation: "golang"
          resolverRepo: local-go
      - name: S_GoPublishBinary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: S_GoBuild
          outputResources:
            - name: R_BuildInfo
          targetRepository: local-go
          autoPublishBuildInfo: true
      - name: S_CreateReleaseBundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: my_go_build
          releaseBundleVersion: 1
          integrations:
            - name: R_GitRepo
          inputResources:
            - name: R_BuildInfo
          outputResources:
            - name: R_ReleaseBundle